# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_ROCKCHIP_MPP_BOUNDARY_KUNIT_TEST) += mpp_request_bounds_test.o
obj-$(CONFIG_ROCKCHIP_MPP_FAULT_KUNIT_TEST) += mpp_fault_injection_test.o
obj-$(CONFIG_ROCKCHIP_MPP_CAPABILITIES_KUNIT_TEST) += mpp_capabilities_test.o
obj-$(CONFIG_ROCKCHIP_MPP_TELEMETRY_KUNIT_TEST) += mpp_telemetry_test.o
obj-$(CONFIG_ROCKCHIP_RGA_FENCE_KUNIT_TEST) += rga_fence_test.o
obj-$(CONFIG_ROCKCHIP_MEDIA_DMA_POLICY_KUNIT_TEST) += media_dma_policy_test.o
